spring.application.name=BackEnd
server.port=8015

spring.datasource.url=${DATABASE_URL}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASS}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# ================================
# WEBPAY PLUS (TEST)
# ================================
webpay.commerce-code=597055555532
webpay.api-key=579B532A7440BB0C9079DED94D31EA1615BACEB56610332264630D42D0A36B1C
webpay.return-url=http://localhost:8015/api/pagos/retorno